experiment:
  data_config:
    strategy: fixed
    test_path: ../data/ml1m_fold_1_test.tsv
    train_path: ../data/ml1m_fold_1_train.tsv
  dataset: ml1m1
  evaluation:
    simple_metrics:
    - nDCG
  models:
    DMF:
      batch_size: 256
      epochs: 10
      item_mlp: (64,32)
      lr: 0.0001
      meta:
        save_recs: true
      n_fold: 1
      reg: 0.001
      similarity: cosine
      user_mlp: (64,32)
  print_results_as_triplets: true
  top_k: 10
