experiment:
  data_config:
    strategy: fixed
    test_path: ../data/popularity_bad_big3/popularity_bad_for_bp_ur_fold_3_test.tsv
    train_path: ../data/popularity_bad_big3/popularity_bad_for_bp_ur_fold_3_train.tsv
  dataset: popularity_bad_big3
  evaluation:
    simple_metrics:
    - nDCG
  models:
    DMF:
      batch_size: 1024
      epochs: 25
      item_mlp: (64,32)
      lr: 0.1
      meta:
        save_recs: true
      n_fold: 1
      similarity: cosine
      user_mlp: (64,32)
  print_results_as_triplets: true
  top_k: 10
