experiment:
  data_config:
    dataset_path: ../data/epinion/epinion.tsv
    strategy: dataset
  dataset: epinion
  evaluation:
    simple_metrics:
    - nDCG
  models:
    DMF:
      batch_size: 256
      epochs: 25
      item_mlp: (64,32)
      lr:
      - 0.1
      - 0.01
      - 0.001
      - 0.0001
      meta:
        save_recs: true
        validation_metric: nDCG
        validation_rate: 1
        verbose: true
      n_fold: 1
      similarity: cosine
      user_mlp: (64,32)
  print_results_as_triplets: true
  splitting:
    test_splitting:
      strategy: random_subsampling
      test_ratio: 0.2
  top_k: 10
