experiment:
  data_config:
    strategy: fixed
    test_path: ../data/popularity_good4/popularity_good_fold_4_test.tsv
    train_path: ../data/popularity_good4/popularity_good_fold_4_train.tsv
  dataset: popularity_good4
  evaluation:
    simple_metrics:
    - nDCG
  models:
    DMF:
      batch_size: 1024
      epochs: 25
      item_mlp: (64,64)
      lr: 0.0001
      meta:
        save_recs: true
      n_fold: 1
      similarity: cosine
      user_mlp: (64,64)
  print_results_as_triplets: true
  top_k: 10
